sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - yarn test
after_success:
  - yarn semantic-release
